services:
  - type: web
    name: aerofetch-api-prod
    runtime: node
    rootDir: backend-new
    buildCommand: npm install && cd ../frontend && npm install && npm run build
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: USE_MOCK_REDIS
        value: "true"
      - key: USE_SIMULATION
        value: "false"
